//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTELIGENTE_SAZÓN.Repositories.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAVORITE_RECIPE
    {
        public int ID_Recipe_Fav { get; set; }
        public Nullable<int> ID_User { get; set; }
        public Nullable<int> ID_Recipe { get; set; }
    
        public virtual RECIPE RECIPE { get; set; }
        public virtual USER USER { get; set; }
    }
}
