//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTELIGENTE_SAZÓN.Repositories.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVENTORY()
        {
            this.REGISTER_FOOD = new HashSet<REGISTER_FOOD>();
            this.USERs = new HashSet<USER>();
        }
    
        public int ID_Invent { get; set; }
        public Nullable<System.DateTime> date_Reg_Invent { get; set; }
        public Nullable<System.DateTime> date_Upda_Invent { get; set; }
        public Nullable<bool> delete_Food_Invent { get; set; }
        public Nullable<int> ID_User { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTER_FOOD> REGISTER_FOOD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER> USERs { get; set; }
    }
}
