//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTELIGENTE_SAZÓN.Repositories.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sazon_inteligenteDBEntities1 : DbContext
    {
        public Sazon_inteligenteDBEntities1()
            : base("name=Sazon_inteligenteDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORY_FOOD> CATEGORY_FOOD { get; set; }
        public virtual DbSet<FAVORITE_RECIPE> FAVORITE_RECIPE { get; set; }
        public virtual DbSet<FOOD> FOODs { get; set; }
        public virtual DbSet<INVENTORY> INVENTORies { get; set; }
        public virtual DbSet<PROFESSIONAL_PROFILE> PROFESSIONAL_PROFILEs { get; set; }
        public virtual DbSet<RECIPE> RECIPEs { get; set; }
        public virtual DbSet<RECIPE_INGREDIENTS> RECIPE_INGREDIENTS { get; set; }
        public virtual DbSet<REGISTER_FOOD> REGISTER_FOOD { get; set; }
        public virtual DbSet<REPORT> REPORTs { get; set; }
        public virtual DbSet<ROLE> ROLEs { get; set; }
        public virtual DbSet<SPECIFICATION_FOOD> SPECIFICATION_FOOD { get; set; }
        public virtual DbSet<UNIT_MEASURE> UNIT_MEASURE { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
    }
}
