//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTELIGENTE_SAZÓN.Repositories.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFESSIONAL_PROFILE
    {
        public int ID_Profile { get; set; }
        public string name_User_Profile { get; set; }
        public string passw_User_Profile { get; set; }
        public string email_User_Profile { get; set; }
        public string cert_Profile { get; set; }
        public Nullable<System.DateTime> date_Regis_Profile { get; set; }
        public Nullable<bool> status_Profile { get; set; }
        public string time_labo { get; set; }
        public Nullable<int> ID_Role { get; set; }
        public Nullable<System.DateTime> Last_Login_Profile { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
