//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTELIGENTE_SAZÓN.Repositories.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECIPE()
        {
            this.FAVORITE_RECIPE = new HashSet<FAVORITE_RECIPE>();
            this.RECIPE_INGREDIENTS = new HashSet<RECIPE_INGREDIENTS>();
        }
    
        public int ID_Recipe { get; set; }
        public string name_Recipe { get; set; }
        public string imag_Recipe { get; set; }
        public string instrucc_Recipe { get; set; }
        public Nullable<bool> delete_Recipe { get; set; }
        public Nullable<int> ID_Ingred { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAVORITE_RECIPE> FAVORITE_RECIPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECIPE_INGREDIENTS> RECIPE_INGREDIENTS { get; set; }
    }
}
