//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTELIGENTE_SAZÓN.Repositories.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIPE_INGREDIENTS
    {
        public int ID_Ingred { get; set; }
        public Nullable<int> amount_Ingred { get; set; }
        public Nullable<int> ID_Unit_Measure { get; set; }
        public Nullable<int> ID_Recipe { get; set; }
        public Nullable<int> ID_Food { get; set; }
    
        public virtual FOOD FOOD { get; set; }
        public virtual RECIPE RECIPE { get; set; }
        public virtual UNIT_MEASURE UNIT_MEASURE { get; set; }
    }
}
