//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTELIGENTE_SAZÓN.Repositories.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTER_FOOD
    {
        public int ID_Regis_Product { get; set; }
        public Nullable<int> amount_Product { get; set; }
        public Nullable<System.DateTime> date_Regis_Food { get; set; }
        public Nullable<System.DateTime> date_Upda_Food { get; set; }
        public Nullable<bool> delete_Food { get; set; }
        public Nullable<int> ID_Invent { get; set; }
        public Nullable<int> ID_Food { get; set; }
        public Nullable<int> ID_Unit_Measure { get; set; }
        public Nullable<int> ID_User { get; set; }
        public Nullable<int> ID_Categ_Food { get; set; }
    
        public virtual CATEGORY_FOOD CATEGORY_FOOD { get; set; }
        public virtual FOOD FOOD { get; set; }
        public virtual INVENTORY INVENTORY { get; set; }
        public virtual UNIT_MEASURE UNIT_MEASURE { get; set; }
        public virtual USER USER { get; set; }
    }
}
