//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTELIGENTE_SAZÓN.Repositories.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPECIFICATION_FOOD
    {
        public int ID_Specif_Food { get; set; }
        public string time_Opet_Days { get; set; }
        public Nullable<bool> delete_Food { get; set; }
        public string sugges_Conser_Food { get; set; }
        public Nullable<int> ID_Food { get; set; }
    
        public virtual FOOD FOOD { get; set; }
    }
}
