//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTELIGENTE_SAZÓN.Repositories.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIT_MEASURE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UNIT_MEASURE()
        {
            this.RECIPE_INGREDIENTS = new HashSet<RECIPE_INGREDIENTS>();
            this.REGISTER_FOOD = new HashSet<REGISTER_FOOD>();
        }
    
        public int ID_Unit_Measure { get; set; }
        public string type_Unit_Measure { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECIPE_INGREDIENTS> RECIPE_INGREDIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTER_FOOD> REGISTER_FOOD { get; set; }
    }
}
