//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTELIGENTE_SAZÓN.Repositories.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.FAVORITE_RECIPE = new HashSet<FAVORITE_RECIPE>();
            this.PROFESSIONAL_PROFILE = new HashSet<PROFESSIONAL_PROFILE>();
            this.REGISTER_FOOD = new HashSet<REGISTER_FOOD>();
        }
    
        public int ID_User { get; set; }
        public string name_User { get; set; }
        public string email_User { get; set; }
        public string phone_User { get; set; }
        public string passw_User { get; set; }
        public Nullable<System.DateTime> date_Regis_User { get; set; }
        public Nullable<int> ID_Role { get; set; }
        public Nullable<int> ID_Invent { get; set; }
        public Nullable<System.DateTime> last_Login_User { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAVORITE_RECIPE> FAVORITE_RECIPE { get; set; }
        public virtual INVENTORY INVENTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROFESSIONAL_PROFILE> PROFESSIONAL_PROFILE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTER_FOOD> REGISTER_FOOD { get; set; }
        public virtual ROLE ROLE { get; set; }
    }
}
